//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer
    {
        public int id { get; set; }
        public string lId { get; set; }
        public string lName { get; set; }
        public string lFaculty { get; set; }
        public string lDepartment { get; set; }
        public string lCenter { get; set; }
        public string lBuilding { get; set; }
        public int lLevel { get; set; }
        public string lRank { get; set; }
    }
}
