//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int id { get; set; }
        public string sCode { get; set; }
        public string sName { get; set; }
        public int offYear { get; set; }
        public int offSemester { get; set; }
        public Nullable<int> lecHours { get; set; }
        public Nullable<int> tutHours { get; set; }
        public Nullable<int> labHours { get; set; }
        public Nullable<int> evaHours { get; set; }
    }
}
